In [3]:
import numpy as np

In [4]:
a = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

arr1 = np.array(a)



In [7]:
arr1.size


12

In [17]:
arr1.ndim

2

In [18]:
arr1.shape

(3, 4)

In [8]:
b = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr2 = np.array(b)

In [9]:
arr2[0]

array([1, 2, 3, 4])

In [10]:
i = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]
arr3 = np.array(i)


In [11]:
arr3[2:3, [3]]

array([[12]])

In [12]:
e = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]
arr4 = np.array(e)

In [13]:
arr4[arr4 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [14]:
np.random.rand(3, 3)

array([[0.34578729, 0.37144563, 0.264094  ],
       [0.23639491, 0.52604719, 0.21629967],
       [0.25512968, 0.96422619, 0.2745196 ]])

In [15]:
s =     [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]]
arr5 = np.array(s)

In [16]:
arr6 = np.expand_dims(arr5, axis = 0)

In [17]:
arr6.ndim

3

In [18]:
i = [[1, 2, 3, 4],
     [5, 6, 7, 8],
    [9, 10, 11, 12]]

arr5 = np.array(i)
arr5.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [19]:
a = [[1, 2, 3, 4], 
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

arr6 = np.array(a)

b = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]
arr7 = np.array(b)


In [20]:
#1]Index wise multiplication

arr6*arr7

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [30]:
#2] Matrix multiplication
import numpy as np

a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Transpose the matrix b
b_T = b.T

# Multiply the matrix a (3x4) with the transposed matrix b_T (4x3)
C = np.dot(a, b_T)
# Alternatively, you can use the @ operator
C = a @ b_T

print(C)

[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [22]:
#3] Add both the matricx

arr6 + arr7

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [23]:
#4] Subtract matrix B from A

arr7 - arr6

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
#5] Divide Matrix B by A

arr7/arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import numpy as np

# Define a NumPy array with a particular byte order
a = np.array([1, 256, 65536], dtype=np.int32)

# Print the original array
print("Original array:", a)

# Swap the byte order of the array
swapped_array = a.byteswap()

# Print the array with byte order swapped
print("Array with swapped byte order:", swapped_array)